[project]
name = "coscientist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "boto3>=1.43.29",
    "fedotmas",
    "google-adk[extensions]>=2.1.0",
    "langchain-text-splitters>=1.1.2",
    "metapub>=0.7.4",
    "openhands-agent-server>=1.24.0",
    "openhands-sdk>=1.24.0",
    "openhands-tools>=1.24.0",
    "openhands-workspace>=1.24.0",
    "opik>=2.0.49",
    "rag-tools",
    "rank-bm25>=0.2.2",
]

[tool.uv.sources]
rag-tools = { git = "https://github.com/fiestaxxl/rag_tools.git" }
fedotmas = { git = "https://github.com//ITMO-NSS-team/FEDOT.MAS.git", subdirectory = "packages/fedotmas" }

[tool.setuptools]
packages = ["CoScientist"]
