version: '3.8'

services:
  streamlit-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8505:8501"
    volumes:
      - /Users/lizzy/Documents/WORK/LLM/PubChemCoScientist/server/data/papers:/app/papers
      - /Users/lizzy/Documents/WORK/LLM/PubChemCoScientist/server/data/parse_results:/app/streamlit_app/parse_results/
      - /Users/lizzy/Documents/WORK/LLM/PubChemCoScientist/server/data/chromadb:/app/streamlit_app/chromadb
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped